CC=gcc
LEX=lex
CFLAGS=
LDFLAGS=-lm
LDLEXFLAGS=-lm -lfl -lc
mojyh_color : scanner.c
	$(CC) $(CFLAGS) -o mojyh_color scanner.c mojyh_color.o $(LDLEXFLAGS)
scanner.c : mojyh_color.o
	$(LEX) -o scanner.c scanner.lex
mojyh_color.o : mojyh_color.c
	$(CC) $(CFLAGS) -c mojyh_color.c -o mojyh_color.o $(LDFLAGS)
clean : 
	rm -rf *.o mojyh_color scanner.c
