CC=gcc
LEX=flex
CFLAGS=
LDFLAGS=
LDLEXFLAGS=-ll -lc
mojyh_color : scanner.c
	$(CC) $(CFLAGS) -o mojyh_color scanner.c mojyh_color.o fmemopen.o $(LDLEXFLAGS)
scanner.c : mojyh_color.o
	$(LEX) -o scanner.c scanner.lex
mojyh_color.o : fmemopen.o
	$(CC) $(CFLAGS) -c mojyh_color.c -o mojyh_color.o $(LDFLAGS)
fmemopen.o : fmemopen.c
	$(CC) $(CFLAGS) -c fmemopen.c -o fmemopen.o

clean : 
	rm -rf *.o mojyh_color scanner.c
